export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-background':             '#2e3230',
        'inverse-on-surface':        '#f5f0e8',
        'on-error-container':        '#690005',
        'inverse-surface':           '#2e3230',
        'on-primary-fixed':          '#002110',
        'on-primary-container':      '#d8f0de',
        'on-primary':                '#ffffff',
        'primary-fixed-dim':         '#8ecf9e',
        'secondary-container':       '#f0e8db',
        'surface-container-highest': '#e4e0d8',
        'primary':                   '#4a7c59',
        'surface-bright':            '#faf6f0',
        'background':                '#faf6f0',
        'on-tertiary':               '#ffffff',
        'on-secondary-fixed-variant':'#4a4538',
        'surface-container-low':     '#f5f1ea',
        'tertiary':                  '#705c30',
        'surface-variant':           '#e4e0d8',
        'on-error':                  '#ffffff',
        'secondary':                 '#6b6358',
        'surface-dim':               '#dbd7cf',
        'surface-container-high':    '#eae6de',
        'on-tertiary-container':     '#554020',
        'primary-fixed':             '#c8e8d0',
        'on-surface':                '#2e3230',
        'primary-container':         '#78a886',
        'error':                     '#b83230',
        'secondary-fixed-dim':       '#d4ccbf',
        'on-surface-variant':        '#4a4e4a',
        'on-primary-fixed-variant':  '#2a6038',
        'on-secondary':              '#ffffff',
        'surface-tint':              '#4a7c59',
        'outline':                   '#74796e',
        'on-secondary-fixed':        '#1e1a13',
        'error-container':           '#ffdad8',
        'surface-container-lowest':  '#ffffff',
        'inverse-primary':           '#8ecf9e',
        'on-secondary-container':    '#5e5548',
        'surface':                   '#faf6f0',
        'secondary-fixed':           '#f0e8db',
        'outline-variant':           '#c4c8bc',
        'tertiary-fixed':            '#f8e0a8',
        'tertiary-fixed-dim':        '#dcc48e',
        'on-tertiary-fixed':         '#221a05',
        'on-tertiary-fixed-variant': '#554020',
        'surface-container':         '#f0ece4',
        'tertiary-container':        '#c4a66a',
      },
      fontFamily: {
        headline: ['Literata', 'serif'],
        display:  ['Literata', 'serif'],
        body:     ['Nunito Sans', 'sans-serif'],
        label:    ['Nunito Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg:      '1rem',
        xl:      '1.5rem',
        '2xl':   '2rem',
        '3xl':   '3rem',
        full:    '9999px',
      },
      boxShadow: {
        soft:   '0 4px 20px rgba(46,50,48,0.06)',
        medium: '0 8px 30px rgba(46,50,48,0.08)',
        nav:    '0 -4px 20px rgba(46,50,48,0.06)',
        card:   '0 4px 20px rgba(46,50,48,0.06), 0 1px 3px rgba(46,50,48,0.04)',
      },
    },
  },
  plugins: [],
}